#!/usr/bin/env python3
"""Concatenate every cleaned doc page into a single llms-full.txt.

Per the llms.txt spec (https://llmstxt.org/), llms-full.txt inlines the full
text of the documentation so an LLM can ingest the whole corpus in one file.
Run after clean_mdx.py so the inlined text is plain Markdown.

Usage: build_llms_full.py ROOT > llms-full.txt
"""
import os
import sys

BASE = "https://docs.polymarket.com"


def url_for(rel: str) -> str:
    path = rel[:-3]                      # drop ".md"
    if path == "index":
        return f"{BASE}/"
    return f"{BASE}/{path}"


def main(root: str):
    pages = []
    for dirpath, _, files in os.walk(root):
        for name in files:
            if not name.endswith(".md") or name == "README.md":
                continue
            full = os.path.join(dirpath, name)
            rel = os.path.relpath(full, root)
            pages.append(rel)

    # index first, then alphabetical by path for deterministic output
    pages.sort(key=lambda p: (p != "index.md", p))

    out = [
        "# Polymarket Documentation — Full Text",
        "",
        "> Complete plain-text mirror of docs.polymarket.com, concatenated for "
        "one-shot LLM ingestion. Generated by scripts/build.sh.",
        "",
    ]
    for rel in pages:
        with open(os.path.join(root, rel), encoding="utf-8") as f:
            body = f.read().strip("\n")
        out.append("---")
        out.append("")
        out.append(body)
        out.append("")
        out.append(f"_Source: {url_for(rel)}_")
        out.append("")

    sys.stdout.write("\n".join(out).rstrip("\n") + "\n")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else ".")
